using Microsoft.CodeAnalysis;
using Cysharp.Text;

namespace Pcysl5edgo.SourceGeneratorTestLibarary;

[Generator(LanguageNames.CSharp)]
public sealed class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            using var builder = ZString.CreateStringBuilder(true);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("namespace Test");
            builder.AppendLine("{");
            builder.AppendLine("    internal sealed class Fab {}");
            builder.AppendLine("}");
            context.AddSource("A.cs", builder.ToString());
        });
    }
}
